import { C, sk, lines, pos, laptop, phone, card, ic, pill, btn, browserBar, nav, phoneTop, scene, I, plate, house, tower, garment, room, beach, mapTile, bars, spark, donut, avatar, stars, calGrid, node, connector } from './lib.mjs';

const tile = (svg, h = 150) => `<div style="height:${h}px;border-radius:14px;overflow:hidden">${svg}</div>`;
const prodCard = (svg, price, accent = C.coral, h = 150) => `<div style="background:#fff;border:1px solid ${C.line};border-radius:18px;padding:12px">${tile(svg, h)}<div class="row" style="justify-content:space-between;margin-top:12px">${lines(['110px','70px'])}<span style="font:800 17px 'Archivo';color:${C.ink}">${price}</span></div><div class="row" style="justify-content:space-between;margin-top:12px"><span></span><span style="padding:7px 14px;border-radius:10px;background:${accent};color:#fff;font:800 14px 'Public Sans'">Add +</span></div></div>`;
const chat = (title, items, top = '#0f5e54', bg = '#efe6da') => `${phoneTop(title, top)}<div class="col" style="padding:18px 16px;gap:12px;background:${bg};height:100%">${items.join('')}</div>`;
const b = (t, dir = 'in') => `<div class="bubble ${dir}">${t}</div>`;
const heroBlock = (accent, w = '60%') => `<div class="col" style="gap:14px;width:${w}">${sk('85%', C.ink, 22)}${sk('60%', C.ink, 22)}${sk('90%', '#e5ddd1', 10)}${sk('70%', '#e5ddd1', 10)}<div class="row" style="margin-top:8px"><span style="width:150px;height:44px;border-radius:12px;background:${accent}"></span><span style="width:120px;height:44px;border-radius:12px;border:2px solid ${C.ink}"></span></div></div>`;
const statCard = (label, value, color, extra = '') => `<div style="background:#fff;border:1px solid ${C.line};border-radius:16px;padding:16px 18px;flex:1"><div class="lbl">${label}</div><div style="font:800 30px 'Archivo';margin-top:6px;color:${C.ink}">${value}</div>${extra || sk('60%', color, 6)}</div>`;
const tableRow = (status, color, amt) => `<div class="row" style="padding:12px 16px;border-bottom:1px solid ${C.line};justify-content:space-between">${avatar('#f1ebe2', '#e0d6c8', 30)}<div style="flex:1;margin-left:4px">${lines(['50%','30%'])}</div><b style="font:700 16px 'Public Sans';width:110px;text-align:right">${amt}</b><span style="margin-left:18px;width:84px;text-align:center;padding:6px 0;border-radius:999px;font:800 13px 'Public Sans';background:${color}22;color:${color}">${status}</span></div>`;
const notif = (icon, bg, title, sub, w = 360) => `<div class="row" style="gap:14px">${ic(icon, bg, 50)}<div class="col" style="gap:6px"><b style="font:800 18px 'Public Sans'">${title}</b><span style="font:500 15px 'Public Sans';color:${C.muted}">${sub}</span></div></div>`;

export const scenes = {
// ===================== Solutions =====================
'solution-restaurant-ordering': () => scene(
  laptop(110, 130, 980, 610, `${browserBar()}${nav(C.coral)}<div class="row" style="padding:8px 30px 22px;align-items:center;gap:30px">${heroBlock(C.coral,'48%')}<div style="flex:1;height:200px;border-radius:20px;overflow:hidden">${plate(C.coral, C.gold, C.mint)}</div></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:18px;padding:0 30px">${prodCard(plate('#d9822b', C.mint, C.coral), 'GHS 85', C.coral, 110)}${prodCard(plate(C.gold, C.coral, '#8bc34a'), 'GHS 70', C.coral, 110)}${prodCard(plate('#c0392b', C.gold, C.mint), 'GHS 95', C.coral, 110)}</div>`) +
  phone(1130, 150, 340, 700, chat('Order assistant', [b('Hi! What would you like today?'), b('2 jollof with chicken, 1 waakye. Pick-up at 1pm', 'out'), b('Great: 3 items, total GHS 255. Tap to pay with MoMo.'), `<div style="background:#fff;border-radius:16px;padding:14px;border:1px solid ${C.line}"><div class="lbl">MoMo payment</div><div style="font:800 26px 'Archivo';margin:6px 0 10px">GHS 255</div>${btn('Pay now', C.gold, C.ink)}</div>`])) +
  card(930, 760, 330, notif(I.check, C.mint, 'Order paid', 'Sent to the kitchen'), '', '') +
  card(60, 60, 250, `<div class="row" style="gap:12px">${ic(I.bolt, C.coral, 44)}<div class="col" style="gap:6px"><b style="font:800 17px 'Public Sans'">Lunch rush</b>${sk('120px', '#e5ddd1', 9)}</div></div>`)
),
'solution-real-estate-listings': () => scene(
  laptop(110, 130, 980, 610, `${browserBar()}${nav(C.mint)}<div class="row" style="padding:4px 30px 18px;gap:12px">${pill('3 bed', C.ink)}${pill('Budget', '#f1ebe2', C.ink)}${pill('Location', '#f1ebe2', C.ink)}${pill('GHS | USD', C.gold, C.ink)}</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:18px;padding:0 30px">${[house(), house('#cfeee7', '#fffaf4', C.ink2, C.coral), house('#fde3b5', '#fff', C.mint, C.gold)].map((h,i)=>`<div style="background:#fff;border:1px solid ${C.line};border-radius:18px;padding:12px">${tile(h, 250)}<div style="margin-top:14px">${lines(['80%','50%'])}</div><div class="row" style="justify-content:space-between;margin-top:14px"><b style="font:800 18px 'Archivo'">${['USD 145k','GHS 1.2m','USD 98k'][i]}</b><span style="padding:8px 12px;border-radius:10px;background:${C.wa};color:#fff;font:800 13px 'Public Sans'">Enquire</span></div></div>`).join('')}</div>`) +
  phone(1130, 150, 340, 700, `<div style="height:290px">${house('#ffd9c9', '#fffaf4', C.coral, C.mint)}</div><div class="col" style="padding:20px;gap:14px"><div class="row" style="gap:8px">${pill('3 bed', '#f1ebe2', C.ink)}${pill('2 bath', '#f1ebe2', C.ink)}</div>${lines(['90%','70%','80%'])}<div style="font:800 28px 'Archivo'">USD 145,000</div>${btn('Enquire on WhatsApp', C.wa)}${btn('Book a viewing', C.ink)}</div>`) +
  card(60, 70, 300, `<div class="row" style="gap:12px">${ic(I.globe, C.ink, 46)}<div class="col" style="gap:6px"><b style="font:800 17px 'Public Sans'">Buyer abroad</b><span style="font:500 15px 'Public Sans';color:${C.muted}">Replied in under a minute</span></div></div>`) +
  card(860, 770, 300, `<div style="height:120px;border-radius:12px;overflow:hidden">${mapTile([[60,70,C.coral],[130,100,C.mint],[160,60,C.gold]])}</div>`, 'padding:12px')
),
'solution-clinic-assistant': () => scene(
  phone(560, 70, 400, 860, chat('Clinic assistant', [b('Hello, are you open on Saturday?'), b('Yes, Saturday 9am to 2pm. Would you like to book a visit?'), b('Yes please, in the morning', 'out'), b('These times are free:'), `<div class="row" style="gap:8px;flex-wrap:wrap">${['9:00','10:00','11:30'].map((t,i)=>pill(t, i==2?C.mint:'#fff', i==2?'#fff':C.ink)).join('')}</div>`, b('11:30 works', 'out'), b('Booked for Saturday 11:30. We\u2019ll remind you the day before.')], '#0f5e54')) +
  card(110, 170, 400, `<div class="row" style="justify-content:space-between;margin-bottom:14px"><b class="mid">Appointments</b>${ic(I.cal, C.coral, 40)}</div>${calGrid([5, 12, 13, 19], C.mint, 42)}`) +
  card(150, 650, 340, notif(I.heart, C.coral, 'Handed to staff', 'Medical questions go to a person')) +
  card(1030, 220, 380, `<div class="lbl">Answered this week</div><div class="row" style="justify-content:space-between;margin-top:10px">${spark([4,6,5,9,8,12,14], C.mint, 210, 90)}${ic(I.chat, C.mint, 56)}</div>`) +
  card(1060, 560, 340, notif(I.check, C.ink, 'Reminder sent', 'Day-before reminder'))
),
'solution-invoice-automation': () => scene(
  laptop(90, 130, 1000, 620, `${browserBar()}<div style="display:grid;grid-template-columns:180px 1fr;height:100%"><div style="background:${C.ink};padding:24px 20px" class="col">${sk('90px', C.paper, 12)}<div style="height:20px"></div>${['80%','70%','85%','60%','75%'].map((w,i)=>`<div class="row" style="gap:10px;padding:8px;border-radius:10px;${i==1?'background:rgba(255,250,244,.12)':''}"><span style="width:16px;height:16px;border-radius:5px;background:${[C.coral,C.mint,C.gold,'#5d7290','#5d7290'][i]}"></span>${sk(w, 'rgba(255,250,244,.35)', 9)}</div>`).join('')}</div><div style="padding:22px 26px" class="col"><div class="row" style="gap:16px">${statCard('Collected', 'GHS 48k', C.mint)}${statCard('Overdue', '3', C.coral)}${statCard('Due soon', '7', C.gold)}</div><div style="background:#fff;border:1px solid ${C.line};border-radius:16px;margin-top:6px">${tableRow('Paid', '#1e9c86', 'GHS 4,200')}${tableRow('Paid', '#1e9c86', 'GHS 1,850')}${tableRow('Reminded', '#c98a12', 'GHS 3,100')}${tableRow('Overdue', C.coral, 'GHS 2,400')}</div><div class="row" style="gap:16px;margin-top:6px"><div style="flex:2;background:#fff;border:1px solid ${C.line};border-radius:16px;padding:14px 18px"><div class="lbl">Cash in, last 8 weeks</div>${spark([3,4,3.5,5,6,5.5,7,8], C.mint, 470, 70)}</div><div style="flex:1;background:#fff;border:1px solid ${C.line};border-radius:16px;padding:14px 18px" class="row">${donut(80, C.coral, 80)}<div style="margin-left:12px">${lines(['70px','50px'])}</div></div></div></div></div>`) +
  card(1140, 120, 330, node(I.doc, C.gold, 'Invoice due in 3 days', 290).replace('class="card row', 'class="row').replace('padding:16px 18px', 'padding:0'), 'padding:18px') +
  card(1140, 330, 330, node(I.chat, C.wa, 'Reminder + MoMo link', 290).replace('class="card row', 'class="row').replace('padding:16px 18px', 'padding:0'), 'padding:18px') +
  card(1140, 540, 330, node(I.check, C.mint, 'Paid, receipt sent', 290).replace('class="card row', 'class="row').replace('padding:16px 18px', 'padding:0'), 'padding:18px') +
  connector(1300, 215, 1300, 330) + connector(1300, 425, 1300, 540) +
  card(1060, 770, 400, `<div class="lbl">Monday 8:00 · owner summary</div><div class="row" style="margin-top:12px;justify-content:space-between">${bars([40,65,50,80,70,95], [C.gold, C.coral], 80, 22, 10)}${donut(72, C.mint, 86)}</div>`, '', 'dark')
),

// ===================== Industries =====================
'industry-real-estate': () => scene(
  laptop(110, 140, 980, 600, `${browserBar()}${nav(C.coral)}<div class="row" style="padding:6px 30px 20px;gap:28px">${heroBlock(C.coral,'44%')}<div style="flex:1;height:230px;border-radius:20px;overflow:hidden">${tower()}</div></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:14px;padding:0 30px">${[house(), house('#cfeee7','#fff',C.ink2,C.coral), house('#fde3b5','#fff',C.mint,C.gold), house('#e8e2f6','#fff',C.coral,C.mint)].map(h=>`<div style="background:#fff;border:1px solid ${C.line};border-radius:16px;padding:10px">${tile(h,110)}<div style="margin-top:10px">${lines(['80%','50%'])}</div></div>`).join('')}</div>`) +
  card(1130, 170, 360, notif(I.chat, C.wa, 'New enquiry', '3-bed townhouse · WhatsApp')) +
  card(1130, 350, 360, `<div class="lbl">Qualified leads</div>${spark([2,3,3,5,4,6,8,9], C.coral, 310, 110)}`) +
  card(1130, 600, 360, `<div class="row" style="justify-content:space-between"><div class="col" style="gap:8px"><b class="mid">Viewing booked</b><span style="font:500 15px 'Public Sans';color:${C.muted}">Saturday · 10:00</span></div>${ic(I.cal, C.gold, 52, C.ink)}</div>`)
),
'industry-diaspora-property': () => scene(
  phone(620, 80, 380, 840, `<div style="height:330px;position:relative">${house('#cfeee7','#fffaf4',C.coral,C.gold)}<span style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:84px;height:84px;border-radius:50%;background:rgba(16,36,63,.85);color:#fff;display:flex;align-items:center;justify-content:center">${I.play}</span></div><div class="col" style="padding:22px;gap:14px"><div class="lbl">Video tour</div>${lines(['90%','65%'])}<div style="font:800 30px 'Archivo'">USD 120,000</div><div class="row" style="gap:8px">${pill('Title checked', '#dff6ee', '#137a68')}${pill('Site visit', '#f1ebe2', C.ink)}</div>${btn('Book a video viewing', C.ink)}${btn('Ask on WhatsApp', C.wa)}</div>`) +
  card(110, 180, 420, `<div class="row" style="gap:14px;margin-bottom:16px">${ic(I.globe, C.mint, 50)}<b class="mid">Buyers in every time zone</b></div>${['London','Toronto','Houston'].map((c,i)=>`<div class="row" style="justify-content:space-between;padding:10px 0;border-top:1px solid ${C.line}"><span style="font:600 17px 'Public Sans'">${c}</span><span style="font:800 15px 'Public Sans';color:${[C.coral,C.mint,C.gold][i]}">Replied instantly</span></div>`).join('')}`) +
  card(150, 640, 360, notif(I.plane, C.coral, 'Visit planned', 'Viewing during your trip home')) +
  card(1060, 250, 380, `<div style="height:200px;border-radius:14px;overflow:hidden">${mapTile([[70,80,C.coral],[140,110,C.mint]])}</div><div class="row" style="justify-content:space-between;margin-top:14px">${lines(['160px','100px'])}${ic(I.pin, C.coral, 44)}</div>`) +
  card(1080, 640, 340, notif(I.shield, C.ink, 'Documents shared', 'Secure, in one place')) +
  connector(530, 300, 620, 380)
),
'industry-private-healthcare': () => scene(
  laptop(110, 140, 980, 600, `${browserBar()}<div style="display:grid;grid-template-columns:1fr 330px;gap:22px;padding:26px 30px;height:100%"><div class="col" style="gap:16px"><div class="row" style="justify-content:space-between"><b class="big">Book a visit</b>${ic(I.cross, C.coral, 48)}</div><div class="row" style="gap:10px">${pill('General', C.ink)}${pill('Dental', '#f1ebe2', C.ink)}${pill('Paediatrics', '#f1ebe2', C.ink)}</div>${calGrid([8, 9, 15, 17, 22], C.mint, 58)}</div><div class="col" style="gap:12px"><div class="lbl">Available times</div>${['08:30','10:00','11:30','14:00','15:30'].map((t,i)=>`<div class="row" style="justify-content:space-between;padding:14px 16px;border-radius:14px;background:${i==2?C.mint:'#fff'};color:${i==2?'#fff':C.ink};border:1px solid ${C.line}"><b style="font:700 18px 'Public Sans'">${t}</b>${sk('80px', i==2?'rgba(255,255,255,.5)':'#e5ddd1', 9)}</div>`).join('')}${btn('Confirm booking', C.coral)}</div></div>`) +
  phone(1150, 220, 300, 600, `${phoneTop('Reminders', C.ink)}<div class="col" style="padding:18px 14px;gap:12px;background:#efe6da;height:100%">${b('Reminder: your visit is tomorrow at 11:30.')}${b('Reply 1 to confirm, 2 to reschedule.')}${b('1', 'out')}${b('Confirmed. See you tomorrow!')}</div>`) +
  card(60, 70, 320, notif(I.heart, C.coral, 'Fewer no-shows', 'Day-before reminders'))
),
'industry-private-schools': () => scene(
  laptop(110, 140, 1000, 610, `${browserBar()}<div class="row" style="padding:22px 28px;justify-content:space-between"><div class="row" style="gap:14px">${ic(I.cap, C.ink, 50)}<b class="big">Admissions</b></div><span style="padding:12px 18px;border-radius:12px;background:${C.coral};color:#fff;font:800 16px 'Public Sans'">Book a school visit</span></div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:14px;padding:0 28px">${[['Enquiry',C.gold,4],['Visit booked',C.mint,3],['Applied',C.coral,2],['Enrolled',C.ink,2]].map(([t,c,n])=>`<div style="background:#f4ede3;border-radius:16px;padding:14px" class="col"><div class="row" style="justify-content:space-between"><b style="font:800 16px 'Public Sans'">${t}</b><span style="width:12px;height:12px;border-radius:50%;background:${c}"></span></div>${Array.from({length:n},()=>`<div style="background:#fff;border-radius:12px;padding:12px;border-left:5px solid ${c}">${lines(['80%','55%'])}</div>`).join('')}</div>`).join('')}</div>`) +
  card(1150, 180, 330, notif(I.cal, C.mint, 'Open day booked', 'Reminder sent to parent')) +
  card(1150, 360, 330, `<div class="lbl">Enrolment enquiries</div>${bars([30,45,40,60,70,65,85,95], [C.gold, C.coral], 120, 22, 12)}`) +
  card(1150, 640, 330, notif(I.users, C.ink, 'Parent follow-up', 'Automatic, every enquiry'))
),
'industry-restaurants-caterers': () => scene(
  phone(170, 90, 380, 820, `<div style="height:250px">${plate(C.coral, C.gold, C.mint)}</div><div class="col" style="padding:20px;gap:14px"><div class="row" style="justify-content:space-between"><b class="mid">Today's menu</b>${pill('Open', '#dff6ee', '#137a68')}</div>${[plate('#d9822b',C.mint,C.coral), plate(C.gold,C.coral,'#8bc34a'), plate('#c0392b',C.gold,C.mint)].map((pl,i)=>`<div class="row" style="gap:12px;background:#fff;border:1px solid ${C.line};border-radius:16px;padding:10px"><div style="width:72px;height:56px;border-radius:10px;overflow:hidden">${pl}</div><div style="flex:1">${lines(['80%','50%'])}</div><b style="font:800 16px 'Archivo'">GHS ${[85,70,95][i]}</b></div>`).join('')}${btn('Order on WhatsApp', C.wa)}</div>`) +
  card(640, 150, 420, `<div class="row" style="justify-content:space-between"><b class="mid">Catering quote</b>${ic(I.doc, C.gold, 44, C.ink)}</div><div style="margin:16px 0">${lines(['90%','75%','85%'])}</div><div class="row" style="justify-content:space-between;padding-top:14px;border-top:1px solid ${C.line}"><span class="lbl">Deposit</span><b style="font:800 24px 'Archivo'">GHS 2,500</b></div><div style="margin-top:14px">${btn('Pay deposit with MoMo', C.coral)}</div>`) +
  card(1120, 200, 360, notif(I.check, C.mint, 'Order paid', 'Ready for pick-up at 1pm')) +
  card(700, 560, 360, `<div class="lbl">Orders this week</div>${bars([40,55,48,70,90,100,75], [C.coral, C.gold], 130, 28, 14)}`) +
  card(1120, 600, 360, notif(I.bolt, C.ink, 'Reorder in one tap', 'For regular office customers'))
),
'industry-hospitality-tourism': () => scene(
  laptop(110, 140, 980, 600, `${browserBar()}<div style="height:240px;position:relative">${beach()}<div style="position:absolute;left:30px;right:30px;bottom:-34px;background:#fff;border-radius:18px;box-shadow:0 14px 30px rgba(16,36,63,.15);padding:16px;display:grid;grid-template-columns:1fr 1fr 1fr 160px;gap:14px">${['Check-in','Check-out','Guests'].map(t=>`<div class="col" style="gap:6px"><span class="lbl">${t}</span>${sk('70%', C.ink, 12)}</div>`).join('')}<span style="border-radius:12px;background:${C.coral};color:#fff;font:800 16px 'Public Sans';display:flex;align-items:center;justify-content:center">Check rates</span></div></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:56px 30px 0">${[room(),beach(),room()].map((r,i)=>`<div style="background:#fff;border:1px solid ${C.line};border-radius:16px;padding:10px">${tile(r,100)}<div class="row" style="justify-content:space-between;margin-top:10px">${lines(['100px','60px'])}<b style="font:800 16px 'Archivo'">USD ${[85,140,110][i]}</b></div></div>`).join('')}</div>`) +
  card(1130, 170, 360, `<div class="row" style="justify-content:space-between;margin-bottom:10px"><b class="mid">Guest reviews</b>${stars(5, 22)}</div>${lines(['95%','80%','60%'])}`) +
  card(1130, 380, 360, `<div class="lbl" style="margin-bottom:12px">Availability</div>${calGrid([10,11,12,13], C.coral, 36)}`) +
  card(1130, 720, 360, notif(I.check, C.mint, 'Direct booking', 'Deposit paid online'))
),
'industry-churches-ministries': () => scene(
  laptop(110, 150, 940, 580, `${browserBar()}<div style="padding:24px 28px" class="col"><div style="height:250px;border-radius:18px;background:linear-gradient(135deg,${C.ink},#24456e);position:relative;overflow:hidden"><div style="position:absolute;inset:0;background:radial-gradient(400px 200px at 70% 30%,rgba(238,180,63,.45),transparent)"></div><span style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:90px;height:90px;border-radius:50%;background:${C.coral};color:#fff;display:flex;align-items:center;justify-content:center">${I.play}</span><span style="position:absolute;left:20px;top:20px">${pill('LIVE', C.coral)}</span></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:10px">${[C.gold,C.mint,C.coral].map(c=>`<div style="background:#fff;border:1px solid ${C.line};border-radius:14px;padding:14px" class="row">${ic(I.cal, c, 42)}<div style="flex:1;margin-left:4px">${lines(['85%','55%'])}</div></div>`).join('')}</div></div>`) +
  phone(1100, 130, 360, 760, `${phoneTop('Give online', C.ink)}<div class="col" style="padding:22px;gap:14px"><div class="lbl">Choose an amount</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px">${['GHS 50','GHS 100','GHS 200','Other'].map((a,i)=>`<div style="padding:16px;border-radius:14px;text-align:center;font:800 18px 'Public Sans';border:2px solid ${i==1?C.mint:C.line};background:${i==1?'#dff6ee':'#fff'}">${a}</div>`).join('')}</div><div class="lbl" style="margin-top:6px">Pay with</div>${['Mobile Money','Card'].map((m,i)=>`<div class="row" style="justify-content:space-between;padding:14px 16px;border-radius:14px;background:#fff;border:1px solid ${C.line}"><b style="font:700 17px 'Public Sans'">${m}</b><span style="width:20px;height:20px;border-radius:50%;border:6px solid ${i?C.line:C.mint}"></span></div>`).join('')}${btn('Give GHS 100', C.coral)}</div>`) +
  card(80, 70, 330, notif(I.heart, C.coral, 'Thank you!', 'Receipt sent by SMS'))
),
'industry-fashion-retail': () => scene(
  laptop(110, 140, 980, 600, `${browserBar()}${nav(C.ink)}<div class="row" style="padding:0 30px 16px;gap:10px">${pill('New in', C.ink)}${pill('Dresses', '#f1ebe2', C.ink)}${pill('Tops', '#f1ebe2', C.ink)}${pill('Bags', '#f1ebe2', C.ink)}</div><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:14px;padding:0 30px">${[garment('#fde3b5',C.coral,'dress'),garment('#cfeee7',C.ink,'tee'),garment('#ffd9c9',C.mint,'bag'),garment('#e8e2f6',C.gold,'dress')].map((g,i)=>`<div style="background:#fff;border:1px solid ${C.line};border-radius:16px;padding:10px">${tile(g,190)}<div class="row" style="justify-content:space-between;margin-top:10px">${lines(['80px','50px'])}<b style="font:800 16px 'Archivo'">GHS ${[450,180,320,520][i]}</b></div></div>`).join('')}</div>`) +
  phone(1140, 160, 330, 690, `${phoneTop('Your bag', C.ink)}<div class="col" style="padding:18px;gap:12px">${[garment('#fde3b5',C.coral,'dress'),garment('#ffd9c9',C.mint,'bag')].map((g,i)=>`<div class="row" style="gap:12px;background:#fff;border:1px solid ${C.line};border-radius:14px;padding:10px"><div style="width:64px;height:64px;border-radius:10px;overflow:hidden">${g}</div><div style="flex:1">${lines(['80%','40%'])}</div><b style="font:800 15px 'Archivo'">GHS ${[450,320][i]}</b></div>`).join('')}<div class="row" style="justify-content:space-between;padding:12px 2px;border-top:1px solid ${C.line}"><span class="lbl">Total</span><b style="font:800 24px 'Archivo'">GHS 770</b></div>${btn('Pay with MoMo', C.gold, C.ink)}${btn('Pay by card', C.ink)}</div>`) +
  card(860, 760, 330, notif(I.bag, C.coral, 'New order', 'Paid · ready to ship'))
),
'industry-events-weddings': () => scene(
  laptop(110, 140, 980, 600, `${browserBar()}${nav(C.coral)}<div style="display:grid;grid-template-columns:2fr 1fr 1fr;grid-template-rows:180px 180px;gap:14px;padding:4px 30px">${[['linear-gradient(135deg,#f2654b,#eeb43f)',I.ring],['linear-gradient(135deg,#24bda4,#10243f)',I.note],['linear-gradient(135deg,#fde3b5,#f2654b)',I.heart],['linear-gradient(135deg,#10243f,#24456e)',I.spark],['linear-gradient(135deg,#eeb43f,#fde3b5)',I.cal]].map(([g,i],k)=>`<div style="border-radius:16px;background:${g};${k==0?'grid-row:span 2;':''}display:flex;align-items:center;justify-content:center;color:rgba(255,250,244,.85)"><span style="width:${k==0?120:64}px;height:${k==0?120:64}px;display:inline-flex;align-items:center;justify-content:center">${i.replace(/width="\d+%" height="\d+%"/,'width="100%" height="100%"')}</span></div>`).join('')}</div>`) +
  phone(1140, 160, 330, 690, `${phoneTop('Check your date', C.coral)}<div class="col" style="padding:18px;gap:12px"><div class="lbl">Pick a date</div>${calGrid([12, 19, 20], C.coral, 30)}<div class="row" style="gap:8px">${pill('Wedding', C.ink)}${pill('120 guests', '#f1ebe2', C.ink)}</div><div class="row" style="justify-content:space-between;padding:10px 2px;border-top:1px solid ${C.line}"><span class="lbl">Deposit</span><b style="font:800 22px 'Archivo'">GHS 3,000</b></div>${btn('Reserve this date', C.coral)}</div>`) +
  card(830, 770, 340, notif(I.check, C.mint, 'Date reserved', 'Deposit received'))
),
'industry-professional-services': () => scene(
  laptop(110, 140, 1000, 610, `${browserBar()}<div style="display:grid;grid-template-columns:170px 1fr;height:100%"><div style="background:${C.ink};padding:22px 18px" class="col">${sk('90px', C.paper, 12)}<div style="height:16px"></div>${['80%','65%','85%','60%'].map((w,i)=>`<div class="row" style="gap:10px;padding:8px;border-radius:10px;${i==0?'background:rgba(255,250,244,.12)':''}"><span style="width:16px;height:16px;border-radius:5px;background:${[C.coral,C.mint,C.gold,'#5d7290'][i]}"></span>${sk(w,'rgba(255,250,244,.35)',9)}</div>`).join('')}</div><div style="padding:20px 24px"><div class="row" style="justify-content:space-between;margin-bottom:14px"><b class="big">Client pipeline</b>${pill('+ New lead', C.coral)}</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:14px">${[['New',C.gold,3],['Proposal sent',C.mint,3],['Won',C.ink,2]].map(([t,c,n])=>`<div style="background:#f4ede3;border-radius:16px;padding:12px" class="col"><b style="font:800 15px 'Public Sans'">${t}</b>${Array.from({length:n},()=>`<div class="row" style="background:#fff;border-radius:12px;padding:12px;gap:10px">${avatar(c,'#f1ebe2',30)}<div style="flex:1">${lines(['85%','50%'])}</div></div>`).join('')}</div>`).join('')}</div></div></div>`) +
  card(1150, 170, 330, notif(I.cal, C.mint, 'Consultation booked', 'Synced to your calendar')) +
  card(1150, 350, 330, `<div class="lbl" style="margin-bottom:10px">Documents</div>${['Engagement letter','Proposal','Invoice'].map((d,i)=>`<div class="row" style="gap:12px;padding:10px 0;border-top:${i?'1px solid '+C.line:'none'}">${ic(I.doc, [C.coral,C.gold,C.ink][i], 38)}<span style="font:600 16px 'Public Sans'">${d}</span></div>`).join('')}`) +
  card(1150, 650, 330, notif(I.mail, C.ink, 'Follow-up sent', 'Automatically, 2 days later'))
),

// ===================== Articles =====================
'article-ai-assistants': () => scene(
  laptop(150, 120, 1000, 640, `<div style="display:grid;grid-template-columns:200px 1fr;height:100%"><div style="background:#f1ebe2;padding:22px 16px" class="col">${sk('120px', C.ink, 12)}<div style="height:12px"></div>${['85%','70%','80%','60%'].map(w=>sk(w,'#ddd2c3',10)).join('')}</div><div class="col" style="padding:26px 30px;gap:16px"><div class="bubble out" style="max-width:70%;font-size:18px">Which clinic near me is good for children?</div><div class="row" style="gap:12px;align-items:flex-start">${ic(I.spark, C.ink, 44, C.gold)}<div class="col" style="gap:12px;flex:1">${lines(['90%','70%'])}${[C.mint,'#e5ddd1','#e5ddd1'].map((c,i)=>`<div class="row" style="gap:14px;background:#fff;border:${i==0?'2px solid '+C.mint:'1px solid '+C.line};border-radius:16px;padding:14px">${avatar(i==0?C.mint:'#f1ebe2', i==0?C.ink:'#e0d6c8', 44)}<div style="flex:1">${lines(['55%','80%'])}</div>${stars(5,18)}${i==0?pill('Recommended', C.mint):''}</div>`).join('')}</div></div><div style="margin-top:auto;border:1px solid ${C.line};background:#fff;border-radius:16px;padding:16px 18px" class="row">${sk('50%','#e5ddd1',10)}<span style="margin-left:auto;width:40px;height:40px;border-radius:12px;background:${C.coral}"></span></div></div></div>`) +
  card(1180, 200, 300, notif(I.star, C.gold, 'Named in the answer', 'Reviews + clear facts')) +
  card(1180, 400, 300, `<div class="lbl">Mentions</div>${spark([1,2,2,3,5,6,8], C.coral, 250, 90)}`) +
  card(1180, 620, 300, notif(I.check, C.mint, 'Profile complete', 'Hours, services, area'))
),
'article-ai-search-visibility': () => scene(
  card(180, 120, 860, `<div class="row" style="gap:14px;border:2px solid ${C.line};border-radius:999px;padding:14px 22px">${ic(I.search, C.ink, 40)}<span style="font:600 20px 'Public Sans';color:${C.ink}">best caterer for a wedding in Ghana</span></div><div style="margin-top:24px;background:#f4ede3;border-radius:20px;padding:22px"><div class="row" style="gap:12px;margin-bottom:14px">${ic(I.spark, C.coral, 40)}<b class="mid">AI overview</b></div>${lines(['95%','88%','92%','60%'])}<div class="row" style="gap:10px;margin-top:18px">${[C.mint,C.gold,C.coral].map(c=>`<span class="row" style="gap:8px;background:#fff;border-radius:999px;padding:8px 14px"><span style="width:14px;height:14px;border-radius:50%;background:${c}"></span>${sk('70px','#e5ddd1',9)}</span>`).join('')}</div></div><div class="col" style="gap:18px;margin-top:22px">${[0,1].map(()=>`<div class="col" style="gap:8px">${sk('40%', '#1a5fb4', 14)}${lines(['90%','70%'])}</div>`).join('')}</div>`, 'padding:30px') +
  card(1100, 170, 340, `<div class="lbl">AI visibility score</div><div class="row" style="gap:18px;margin-top:10px">${donut(78, C.mint, 120)}${lines(['90px','60px','80px'])}</div>`) +
  card(1100, 450, 340, `<div class="lbl">Cited as a source</div>${spark([2,2,3,4,4,6,7,9], C.coral, 290, 100)}`) +
  card(1100, 700, 340, notif(I.check, C.ink, 'Facts consistent', 'Website, maps and listings'))
),
'article-local-seo-gbp': () => scene(
  pos(110, 110, 900, 780, `<div style="width:100%;height:100%;border-radius:28px;overflow:hidden;box-shadow:0 40px 90px rgba(0,0,0,.5)">${mapTile([[60,58,C.coral],[120,95,C.mint],[150,45,C.gold],[90,120,C.ink]])}</div>`) +
  card(780, 200, 420, `<div style="height:150px;border-radius:14px;overflow:hidden;margin-bottom:16px">${house('#cfeee7','#fff',C.coral,C.mint)}</div>${sk('70%', C.ink, 16)}<div class="row" style="gap:10px;margin:12px 0"><b style="font:800 18px 'Public Sans'">4.8</b>${stars(5,20)}</div>${lines(['85%','60%'])}<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:16px">${[[I.pin,'Directions',C.mint],[I.phone,'Call',C.coral],[I.globe,'Website',C.ink]].map(([i,t,c])=>`<div class="col" style="align-items:center;gap:8px">${ic(i,c,46)}<span style="font:700 14px 'Public Sans'">${t}</span></div>`).join('')}</div>`) +
  card(1240, 220, 270, `<div class="lbl">Map views</div>${spark([3,4,4,6,7,8,10], C.coral, 220, 90)}`) +
  card(1240, 430, 270, `<div class="row" style="gap:10px;margin-bottom:10px">${avatar(C.gold,C.coral,36)}${stars(5,16)}</div>${lines(['95%','70%'])}<div style="margin-top:12px;padding:10px;border-radius:10px;background:#f4ede3">${lines(['80%'])}</div>`) +
  card(1240, 690, 270, notif(I.check, C.mint, 'Reply posted', 'Within 24 hours', 220))
),
'article-mobile-money': () => scene(
  phone(600, 70, 400, 860, `${phoneTop('Checkout', C.ink)}<div class="col" style="padding:22px;gap:14px"><div class="row" style="justify-content:space-between"><span class="lbl">Order total</span><b style="font:800 30px 'Archivo'">GHS 640</b></div><div class="lbl" style="margin-top:8px">Pay with</div>${[['Mobile Money',C.gold,true],['Card',C.ink,false],['Bank transfer',C.mint,false]].map(([m,c,on])=>`<div class="row" style="gap:12px;padding:16px;border-radius:16px;background:${on?'#fff7e6':'#fff'};border:2px solid ${on?C.gold:C.line}">${ic(on?I.phone:I.brief, c, 40, on?C.ink:'#fff')}<b style="font:700 18px 'Public Sans';flex:1">${m}</b><span style="width:22px;height:22px;border-radius:50%;border:7px solid ${on?C.gold:C.line}"></span></div>`).join('')}<div style="background:#f4ede3;border-radius:16px;padding:16px" class="col"><span class="lbl">MoMo number</span>${sk('60%', C.ink, 14)}</div>${btn('Pay GHS 640', C.coral)}<div class="row" style="gap:8px;justify-content:center;color:${C.muted};font:600 14px 'Public Sans'"><span style="width:18px;height:18px;display:inline-flex;color:${C.mint}">${I.shield.replace('58%','100%').replace('58%','100%')}</span>Secure payment</div></div>`) +
  card(150, 200, 380, notif(I.bolt, C.gold, 'Approve on your phone', 'Enter your PIN to confirm', 320)) +
  card(150, 420, 380, `<div class="lbl">Checkout completion</div>${spark([3,3.5,4,5,6,7.5,8.5], C.mint, 330, 100)}`) +
  card(1080, 260, 360, notif(I.check, C.mint, 'Payment received', 'Order confirmed automatically')) +
  card(1080, 480, 360, notif(I.mail, C.ink, 'Receipt sent', 'By SMS and email')) +
  card(1080, 700, 360, notif(I.shield, C.coral, 'No screenshots', 'Verified by the provider'))
),
'article-follow-up': () => scene(
  card(140, 140, 760, `<div class="row" style="justify-content:space-between;margin-bottom:18px"><b class="big">Lead follow-up</b>${pill('Every lead', C.mint)}</div>${[['New enquiry','Instant reply sent',C.coral,I.chat],['Day 1','Questions answered',C.gold,I.check],['Day 3','Helpful follow-up',C.mint,I.mail],['Day 7','Booked a call',C.ink,I.cal]].map(([t,d,c,i],k)=>`<div class="row" style="gap:18px;padding:16px 0;${k?'border-top:1px solid '+C.line:''}">${ic(i,c,52)}<div class="col" style="gap:6px;flex:1"><b style="font:800 19px 'Public Sans'">${t}</b><span style="font:500 16px 'Public Sans';color:${C.muted}">${d}</span></div>${sk('140px','#e5ddd1',10)}</div>`).join('')}`, 'padding:30px') +
  phone(1010, 110, 360, 780, `${phoneTop('Leads', C.ink)}<div class="col" style="padding:18px 14px;gap:12px;background:#efe6da;height:100%">${[[C.coral,'New lead'],[C.gold,'Follow-up due'],[C.mint,'Replied'],[C.ink,'Call booked']].map(([c,t])=>`<div class="row" style="gap:12px;background:#fff;border-radius:16px;padding:14px">${avatar(c,'#f1ebe2',40)}<div class="col" style="gap:6px;flex:1"><b style="font:800 16px 'Public Sans'">${t}</b>${sk('80%','#e5ddd1',9)}</div></div>`).join('')}</div>`) +
  card(1340, 640, 210, `<div class="lbl">Response</div><div class="big" style="margin-top:6px">Fast</div>${sk('70%', C.mint, 6)}`)
),
'article-whatsapp-automation': () => scene(
  node(I.chat, C.wa, 'Customer message', 300, true).replace('class="card', 'class="abs card').replace('style="', 'style="left:110px;top:170px;') +
  node(I.spark, C.coral, 'Menu & answers', 300, true).replace('class="card', 'class="abs card').replace('style="', 'style="left:110px;top:370px;') +
  node(I.bag, C.gold, 'Take the order', 300, true).replace('class="card', 'class="abs card').replace('style="', 'style="left:500px;top:270px;') +
  node(I.phone, C.mint, 'MoMo payment link', 300, true).replace('class="card', 'class="abs card').replace('style="', 'style="left:500px;top:470px;') +
  node(I.check, C.mint, 'Confirm + notify team', 300, true).replace('class="card', 'class="abs card').replace('style="', 'style="left:300px;top:680px;') +
  connector(410, 210, 500, 310) + connector(410, 410, 500, 510) + connector(650, 550, 600, 680) +
  phone(1000, 90, 380, 820, chat('Business chat', [b('Hi, can I order for delivery?'), b('Of course! Reply with a number:<br>1 Menu  2 Order  3 Talk to us'), b('2', 'out'), b('What would you like, and where should we deliver?'), b('2 large trays, East Legon', 'out'), b('Total GHS 480. Pay with MoMo here:'), `<div style="background:#fff;border-radius:14px;padding:12px">${btn('Pay with MoMo', C.gold, C.ink)}</div>`]))
),

// ===================== Divisions =====================
'division-web-commerce': () => scene(
  laptop(110, 150, 960, 590, `${browserBar()}${nav(C.coral)}<div class="row" style="padding:10px 30px 24px;gap:30px">${heroBlock(C.coral,'50%')}<div style="flex:1;height:200px;border-radius:20px;overflow:hidden">${garment('#ffd9c9', C.coral, 'bag')}</div></div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;padding:0 30px">${[0,1,2].map(i=>`<div style="background:#fff;border:1px solid ${C.line};border-radius:16px;padding:16px" class="row">${ic([I.bolt,I.phone,I.check][i],[C.coral,C.mint,C.gold][i],44)}<div style="flex:1;margin-left:6px">${lines(['85%','55%'])}</div></div>`).join('')}</div>`) +
  phone(1120, 170, 330, 680, `${phoneTop('Shop', C.ink)}<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:14px">${[garment('#fde3b5',C.coral,'dress'),garment('#cfeee7',C.ink,'tee'),garment('#ffd9c9',C.mint,'bag'),garment('#e8e2f6',C.gold,'tee')].map(g=>`<div style="background:#fff;border-radius:12px;padding:6px;border:1px solid ${C.line}">${tile(g,110)}<div style="margin-top:8px">${sk('70%','#e5ddd1',8)}</div></div>`).join('')}</div><div style="padding:0 14px">${btn('Checkout', C.coral)}</div>`) +
  card(70, 70, 300, notif(I.bolt, C.gold, 'Fast on mobile', 'Built for 3G/4G', 240))
),
'division-growth': () => scene(
  card(110, 130, 760, `<div class="row" style="justify-content:space-between"><b class="big">Growth dashboard</b>${pill('This month', '#f1ebe2', C.ink)}</div><div class="row" style="gap:14px;margin:20px 0">${statCard('Enquiries', '↑', C.mint)}${statCard('Cost per lead', '↓', C.coral)}${statCard('Calls', '↑', C.gold)}</div>${spark([3,4,3.6,5,6,5.6,7,8.2,9], C.coral, 700, 220)}`, 'padding:30px') +
  card(930, 140, 300, `<div style="height:150px;border-radius:12px;background:linear-gradient(135deg,${C.coral},${C.gold});display:flex;align-items:center;justify-content:center;color:#fff"><span style="width:70px;height:70px;display:inline-flex">${I.bolt.replace('58%','100%').replace('58%','100%')}</span></div><div style="margin:14px 0">${lines(['90%','60%'])}</div>${btn('Learn more', C.ink)}`) +
  card(1260, 140, 260, `<div class="lbl">Ad spend split</div><div style="margin-top:10px">${donut(64, C.mint, 150)}</div>`) +
  card(930, 560, 590, `<div class="row" style="gap:14px;border:2px solid ${C.line};border-radius:999px;padding:12px 18px;margin-bottom:16px">${ic(I.search, C.ink, 34)}${sk('50%','#e5ddd1',10)}</div>${[0,1].map(i=>`<div class="col" style="gap:8px;padding:10px 0">${i==0?pill('Top result', C.mint):''}${sk('55%', '#1a5fb4', 13)}${lines(['90%','70%'])}</div>`).join('')}`) +
  card(130, 780, 320, notif(I.users, C.coral, 'Weekly report', 'Plain-English results', 260))
),
'division-brand': () => scene(
  card(110, 120, 620, `<div class="lbl" style="margin-bottom:16px">Colour</div><div style="display:grid;grid-template-columns:repeat(5,1fr);gap:12px">${[C.ink,C.coral,C.mint,C.gold,'#e8dccb'].map(c=>`<div><div style="height:130px;border-radius:16px;background:${c}"></div>${sk('70%','#e5ddd1',8)}</div>`).join('')}</div><div class="lbl" style="margin:26px 0 10px">Type</div><div class="row" style="gap:30px;align-items:flex-end"><span style="font:800 130px/0.9 'Archivo';color:${C.ink}">Aa</span><div class="col" style="gap:12px;flex:1">${sk('90%', C.ink, 20)}${sk('70%', C.ink, 14)}${lines(['95%','85%','60%'])}</div></div>`, 'padding:30px') +
  card(790, 120, 330, `<div style="height:230px;border-radius:16px;background:${C.ink};display:flex;align-items:center;justify-content:center"><svg width="120" height="120" viewBox="0 0 120 120"><circle cx="48" cy="60" r="34" fill="${C.coral}"/><circle cx="76" cy="60" r="34" fill="${C.mint}" opacity=".85"/><circle cx="62" cy="36" r="14" fill="${C.gold}"/></svg></div><div class="lbl" style="margin-top:14px">Logo mark</div>`) +
  card(1160, 120, 330, `<div style="height:230px;border-radius:16px;background:#f4ede3;display:flex;align-items:center;justify-content:center"><svg width="130" height="130" viewBox="0 0 120 120"><rect x="20" y="20" width="80" height="80" rx="24" fill="${C.ink}"/><path d="M42 74l18-30 18 30z" fill="${C.gold}"/></svg></div><div class="lbl" style="margin-top:14px">App icon</div>`) +
  pos(830, 520, 560, 320, `<div style="position:relative;width:100%;height:100%"><div style="position:absolute;left:70px;top:0;width:440px;height:250px;border-radius:18px;background:${C.coral};transform:rotate(-7deg);box-shadow:0 30px 60px rgba(0,0,0,.4)"></div><div style="position:absolute;left:20px;top:50px;width:440px;height:250px;border-radius:18px;background:${C.paper};box-shadow:0 30px 60px rgba(0,0,0,.45);padding:30px" class="col"><svg width="56" height="56" viewBox="0 0 120 120"><circle cx="48" cy="60" r="34" fill="${C.coral}"/><circle cx="76" cy="60" r="34" fill="${C.mint}" opacity=".85"/></svg><div style="margin-top:auto">${sk('55%', C.ink, 16)}<div style="height:10px"></div>${lines(['40%','50%'])}</div></div></div>`) +
  card(150, 760, 320, notif(I.check, C.mint, 'Brand guidelines', 'One consistent look', 260))
),
'division-business-technology': () => scene(
  card(560, 330, 480, `<div class="col" style="align-items:center;gap:14px;padding:16px 0">${ic(I.users, C.ink, 90)}<b class="big">Your team</b>${sk('60%','#e5ddd1',10)}</div>`) +
  [[I.mail,C.coral,'Business email',150,120],[I.cloud,C.mint,'Shared files',1130,120],[I.cal,C.gold,'Calendars',150,720],[I.users,C.ink,'CRM',1130,720],[I.shield,C.coral,'Security & backups',640,80],[I.gear,C.mint,'IT support',640,800]].map(([i,c,t,x,y])=>card(x,y,320, notif(i,c,t,'Set up and managed',260))).join('') +
  connector(470, 170, 600, 400) + connector(1130, 170, 1000, 400) + connector(470, 770, 600, 560) + connector(1130, 770, 1000, 560) + connector(800, 175, 800, 330) + connector(800, 800, 800, 600)
),
'division-ai-automation': () => scene(
  pos(650, 360, 300, 300, `<div style="width:300px;height:300px;border-radius:50%;background:radial-gradient(circle,${C.coral},#b8432f);box-shadow:0 0 0 30px rgba(242,101,75,.15),0 0 0 70px rgba(242,101,75,.07),0 40px 90px rgba(0,0,0,.5);display:flex;align-items:center;justify-content:center;color:#fff"><span style="width:150px;height:150px;display:inline-flex">${I.spark.replace('62%','100%').replace('62%','100%')}</span></div>`) +
  node(I.chat, C.wa, 'WhatsApp assistant', 320).replace('class="card', 'class="abs card').replace('style="', 'style="left:130px;top:170px;') +
  node(I.doc, C.gold, 'Invoices & reminders', 320).replace('class="card', 'class="abs card').replace('style="', 'style="left:1150px;top:170px;') +
  node(I.cal, C.mint, 'Bookings', 320).replace('class="card', 'class="abs card').replace('style="', 'style="left:130px;top:740px;') +
  node(I.users, C.ink, 'Lead follow-up', 320).replace('class="card', 'class="abs card').replace('style="', 'style="left:1150px;top:740px;') +
  node(I.bolt, C.coral, 'Reports', 320).replace('class="card', 'class="abs card').replace('style="', 'style="left:640px;top:90px;') +
  connector(450, 215, 680, 420) + connector(1150, 215, 920, 420) + connector(450, 785, 680, 600) + connector(1150, 785, 920, 600) + connector(800, 180, 800, 360)
),
'division-software': () => scene(
  laptop(110, 150, 940, 580, `<div style="background:#0f1c2e;height:100%;display:grid;grid-template-columns:180px 1fr"><div style="background:#0b1625;padding:20px 14px" class="col">${['70%','55%','80%','60%','75%','50%'].map((w,i)=>sk(w, i==2?C.gold:'rgba(255,250,244,.18)', 9)).join('')}</div><div style="padding:22px 26px" class="col">${[[['14%',C.coral],['30%',C.paper],['18%',C.mint]],[['8%','transparent'],['22%',C.gold],['34%','rgba(255,250,244,.4)']],[['8%','transparent'],['16%',C.mint],['26%',C.paper],['12%',C.coral]],[['16%','transparent'],['40%','rgba(255,250,244,.35)']],[['16%','transparent'],['20%',C.gold],['24%',C.mint]],[['8%','transparent'],['12%',C.coral]],[['14%',C.coral],['26%',C.paper]],[['8%','transparent'],['30%','rgba(255,250,244,.35)'],['16%',C.gold]],[['8%','transparent'],['18%',C.mint],['22%',C.paper]],[['0%','transparent'],['10%',C.coral]]].map(r=>`<div class="row" style="gap:10px">${r.map(([w,c])=>`<div style="width:${w};height:12px;border-radius:6px;background:${c}"></div>`).join('')}</div>`).join('')}<div class="row" style="margin-top:auto;gap:10px">${pill('Build passing', '#1e9c86')}${pill('Deployed', C.ink, C.paper)}</div></div></div>`) +
  phone(1100, 130, 320, 660, `${phoneTop('Client portal', C.ink)}<div class="col" style="padding:16px;gap:12px"><div class="row" style="gap:10px">${statCard('Open', '4', C.coral)}${statCard('Done', '12', C.mint)}</div>${[C.coral,C.gold,C.mint].map(c=>`<div class="row" style="gap:10px;background:#fff;border:1px solid ${C.line};border-radius:14px;padding:12px">${ic(I.doc,c,36)}<div style="flex:1">${lines(['80%','50%'])}</div></div>`).join('')}${btn('New request', C.coral)}</div>`) +
  card(70, 70, 310, notif(I.code, C.ink, 'Custom integrations', 'Your tools, connected', 250)) +
  card(1180, 820, 300, notif(I.check, C.mint, 'Tested & documented', 'Handed over to you', 240))
),
};
